# Generated by Django 5.2.7 on 2026-01-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='actual_combo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
