# Generated by Django 5.2.7 on 2026-01-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0002_combo_actual_combo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='max_apply_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
