# Generated by Django 5.2.7 on 2025-12-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
